language: node_js
node_js: '10.15.3'
branches:
  only:
  - master
  - /^greenkeeper/.*$/
  - /^feature/.*$/
cache:
  yarn: true
  directories:
    - node_modules
before_install:
  - yarn global add bs-platform
install:
  - yarn install
script:
  - npm link bs-platform
  - npm link webpack-cli
  - npm link webpack
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  verbose: true
  on:
    branch: master
