language: node_js
node_js: '10.15.3'
branches:
  only:
  - master
  - /^greenkeeper/.*$/
  - /^feature/.*$/
# cache:
#   directories:
#     - node_modules
before_install:
  - npm i -g add bs-platform
script:
  - npm link
  - npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  verbose: true
  on:
    branch: master
